### ISSUE TITLE
Fall through everything, nothing is ground.

### ISSUE THREAD

**Issue by CRsquared64** [DaniDevy/FPS_Movement_Rigidbody#27]
My version is 2019.4, ground doesnt come up as an optuin in what is ground, so i fall through everything.

**Comment by rzaozcnn** [comment]
Who are u bro . I did not understand anything.

24 Kas 2020 Sal 22:05 tarihinde TheMaster6417 <notifications@github.com>
şunu yazdı:

**Comment by Adham4678** [comment]
Dude you need to make a layer callled ground for the player.
